### ISSUE TITLE
Error caused by empty line in manifest

### ISSUE THREAD

**Issue by scripsi** [Gadgetoid/dir2uf2#15]
## Issue
A blank line (or even a new line at the end) in a manifest file causes an error in pathlib.Path.glob():

```
Traceback (most recent call last):
  File "/home/scripsi/project/build/dir2uf2/dir2uf2", line 190, in <module>
    copy_manifest_or_dir(lfs, args.source_dir)
  File "/home/scripsi/project/build/dir2uf2/dir2uf2", line 187, in copy_manifest_or_dir
    copy_files(lfs, source_dir.glob(item), source_dir)
  File "/home/scripsi/project/build/dir2uf2/dir2uf2", line 154, in copy_files
    for src in todo:
  File "/usr/lib/python3.12/pathlib.py", line 1089, in glob
    raise ValueError("Unacceptable pattern: {!r}".format(pattern))
ValueError: Unacceptable pattern: ''
```
## Solution
Test for a non-blank `item` in the `todo` list in `copy_manifest_or_dir()` before passing it to the `copy_files()` call:

```python
def copy_manifest_or_dir(lfs, source_dir):
    if args.manifest is None:
        print(f"Copying directory: {source_dir}")
        # Walk the entire source dir and copy *everything*
        search_path = os.path.join("**", "*")
        copy_files(lfs, source_dir.glob(search_path), source_dir)

    else:
        print(f"Using manifest: {args.manifest}")
        # Copy files/globs listed in the manifest relative to the source dir
        todo = open(args.manifest, "r").read().split("\n")
        for item in todo:
            if item: # <<< test for non-blank item here!
                parent_dir = pathlib.Path(item).parent
                lfs.makedirs(str(parent_dir), exist_ok=True)
                copy_files(lfs, source_dir.glob(item), source_dir)

```

System on which error occurred:
-  Ubuntu 24.04.1 LTS
-  Python 3.12.3
-  Cython==0.29.37
-  littlefs-python==0.12.0
-  dir2uf2 release 0.0.10

**Comment by Gadgetoid** [comment]
I think this bit me too, I need to work on refining the manifest parsing 😬

**Comment by Gadgetoid** [comment]
This might have been fixed by https://github.com/Gadgetoid/dir2uf2/commit/fa7e80d3aa6064a557d32043d223a6f9c9445254

Ran into an error with whitespace at the end of a manifest line, too.

**Comment by Gadgetoid** [comment]
I think (hope) I have fixed this in 0.1.0!
